# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caf134a126c2b741dc06ced8ffd7282a75328d2b1643045e3f710af611acf08639dd6349c02f4debf4fe8169493346aaaf4320a0abbe80e6960c8b91549ba910

test:
  secret_key_base: c79d98177a5ba2ef8070c1e7a66aeecc2a0b3b774cb91563411f42d55160d0d72daf661233f65814e9e30243480774609fff5a76f2a4be43d09a6fbd444b4e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
